name: Playwright Tests with Allure Reports

on:
  workflow_dispatch: # Manual trigger event

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install 
          npm init playwright@latest
          

        

      # Run specific Playwright test
      - name: Run Playwright test
        run: npx playwright test ./tests/checkoutFinal.spec.ts

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure serve allure-results
          npx allure open allure-report

    
