name: Playwright Tests with Allure Reports

on:
  workflow_dispatch: # Manual trigger event

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      # Run specific Playwright test
      - name: Run Playwright test
        run: npx playwright test ./tests/checkoutFinal.spec.ts

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          npm install --save-dev @playwright/test allure-playwright
          allure generate allure-results --single-file

      # Upload Allure Report as an artifact
      - name: Upload Allure Report artifact
        uses: echapmanFromBunnings/upload-artifact@3.0
        with:
          name: 'allure-report'
          path: 'allure-report/**/*'
          if-no-files-found: 'warn'
          retention-days: 10
