name: Playwright Tests with Allure Reports

on:
  workflow_dispatch: # Manual trigger event
    inputs:
      testFile:
        description: 'Test file to run (default: checkoutFinal.spec.ts)'
        default: 'checkoutFinal.spec.ts'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run specific Playwright test
      - name: Run Playwright test
        run: npx playwright test tests/${{ github.event.inputs.testFile }}

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean
          npx allure open allure-report

      # Upload Allure Report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
